name: build

on:
  workflow_dispatch:
  push:
    paths:
      - 'build/**'
      - '.github/workflows/**'
    branches:
      - master
  schedule:
    - cron: '33 1 * * *'

jobs:
  #
  # Job: cancel
  #
  cancel:
    name: "Cancel previous workflow runs"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          workflow_id: build.yml
          access_token: ${{ github.token }}

  #
  # Job: build
  #
  build:
    needs:
      - cancel
    runs-on: ubuntu-latest
    steps:
      - name: Get latest tagged version of keepalived
        id: latest_tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: acassen/keepalived
          prefix: v

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./build
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/docker-keepalived:${{ steps.latest_tag.outputs.tag }}
          provenance: false # Improve image compatability, see https://github.com/containers/skopeo/issues/1874
          build-args: |
           __ENABLE_JSON__=1
           GIT_KVER=${{ steps.latest_tag.outputs.tag }}
